clone:
  recursive: true

matrix:
  TARGET_PLATFORM:
    - linux-386
    - linux-amd64
    - linux-arm
    - darwin-amd64
    - windows-386
    - windows-amd64

compose:
  mqtt:
    image: ansi/mosquitto

build:
  image: htdvisser/ttnbuild
  pull: true
  environment:
    - RELEASE_DIR=release/branch/$$BRANCH
  commands:
    # ttnbuild already contains dependencies, so we copy them:
    - rsync -a /go/src/ /drone/src/
    - make deps
    - make build package
  when:
    branch: [master, develop]

publish:
  azure_storage:
    image: htdvisser/drone-azure-storage
    account_key: $$AZURE_STORAGE_KEY
    storage_account: ttnreleases
    container: release
    source: release/
    when:
      branch: [master, develop]

  dockerhub:
    repo: thethingsnetwork/ttn
    token: $$DOCKER_TOKEN
    when:
      branch: master
      matrix:
        TARGET_PLATFORM: linux-amd64
