matrix:
  GOOS:
    - linux
    - darwin
    - windows
  GOARCH:
    - "386"
    - amd64

compose:
  mqtt:
    image: ansi/mosquitto

build:
  image: htdvisser/ttnbuild
  pull: true
  commands:
    # ttnbuild already contains dependencies, so we copy them:
    - rsync -a /go/src/ /drone/src/
    # and get the ones that we missed in ttnbuild
    - GOOS=$$GOOS GOARCH=$$GOARCH go get -d -v ./...
    - ./build_binaries.sh $$GOOS $$GOARCH
  when:
    branch: [master, develop]

publish:
  azure_storage:
    image: htdvisser/drone-azure-storage
    account_key: $$AZURE_STORAGE_KEY
    storage_account: ttnreleases
    container: release
    source: release/
    when:
      branch: [master, develop]

  dockerhub:
    repo: thethingsnetwork/ttn
    token: $$DOCKER_TOKEN
    when:
      branch: master
      matrix:
        GOOS: linux
        GOARCH: amd64
